version: "3.8"

services:
  fastapi:
    image: postgres:14-alpine
    ports:
      - 5438:5432
    volumes:
      - 'stakewolle_testing_task:/var/lib/postgresql/data'
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_NAME: postgres
  redis:
    image: redis:6-alpine
    ports:
    - 6379:6379
    volumes:
      - redis:/data

volumes:
  stakewolle_testing_task:
  redis: