"""! use hierarchical model for referral system

Revision ID: 615d01317a26
Revises: 660f6722e097
Create Date: 2024-03-14 13:44:23.055185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '615d01317a26'
down_revision: Union[str, None] = '660f6722e097'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('referral_user')
    op.add_column('user', sa.Column('referrer_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'referral_code', ['referrer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'referrer_id')
    op.create_table('referral_user',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('referral_code_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('referral_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.CheckConstraint('referral_code_id <> referral_id', name='check_referral_and_referrer_and_not_the_same_person'),
    sa.ForeignKeyConstraint(['referral_code_id'], ['referral_code.id'], name='referral_user_referral_code_id_fkey'),
    sa.ForeignKeyConstraint(['referral_id'], ['user.id'], name='referral_user_referral_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='referral_user_pkey'),
    sa.UniqueConstraint('referral_code_id', name='referral_user_referral_code_id_key'),
    sa.UniqueConstraint('referral_id', name='referral_user_referral_id_key')
    )
    # ### end Alembic commands ###
