"""= Set unique constraints

Revision ID: 660f6722e097
Revises: 67067fbb7ddc
Create Date: 2024-03-14 12:46:25.489917

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '660f6722e097'
down_revision: Union[str, None] = '67067fbb7ddc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'referral_code', ['code'])
    op.create_unique_constraint(None, 'referral_user', ['referral_code_id'])
    op.create_unique_constraint(None, 'referral_user', ['referral_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'referral_user', type_='unique')
    op.drop_constraint(None, 'referral_user', type_='unique')
    op.drop_constraint(None, 'referral_code', type_='unique')
    # ### end Alembic commands ###
